export const Products = [
  {
    asin: "B08CL8XF75",
    product_title:
      "Panasonic 20L Solo Microwave Oven (NN-ST26JMFDG, Silver, 51 Auto Menus)",
    product_price: "₹6,290",
    product_original_price: "₹7,490",
    currency: "INR",
    product_star_rating: "4.3",
    product_num_ratings: 5876,
    product_url: "https://www.amazon.in/dp/B08CL8XF75",
    product_photo:
      "https://m.media-amazon.com/images/I/61Md+j4GC3L._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹6,290",
    is_best_seller: false,
    is_amazon_choice: true,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "2K+ bought in past month",
    delivery: "FREE delivery by Tue, 20 Aug, 7:00 am - 9:00 pm",
    has_variations: false,
  },
  {
    asin: "B0BK1KS6ZD",
    product_title:
      "Daikin 1.5 Ton 3 Star Inverter Split AC (Copper, PM 2.5 Filter, Triple Display, Dew Clean Technology, Coanda Airflow, 2023 Model, MTKL50U, White)",
    product_price: "₹36,990",
    product_original_price: "₹58,400",
    currency: "INR",
    product_star_rating: "3.7",
    product_num_ratings: 3194,
    product_url: "https://www.amazon.in/dp/B0BK1KS6ZD",
    product_photo:
      "https://m.media-amazon.com/images/I/61pzTsT7ZgL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹36,990",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "1K+ bought in past month",
    delivery: "FREE delivery by Tue, 20 Aug, 7:00 am - 9:00 pm",
    has_variations: false,
  },
  {
    asin: "B09R4SF5SP",
    product_title:
      "Daikin 0.8 Ton 3 Star, Fixed Speed Split AC (Copper, PM 2.5 Filter, 2022 Model, FTL28U, White)",
    product_price: "₹25,990",
    product_original_price: "₹37,400",
    currency: "INR",
    product_star_rating: "4",
    product_num_ratings: 3259,
    product_url: "https://www.amazon.in/dp/B09R4SF5SP",
    product_photo:
      "https://m.media-amazon.com/images/I/61mOVGinDdL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹25,990",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "600+ bought in past month",
    delivery: "FREE delivery by Tue, 20 Aug, 7:00 am - 9:00 pm",
    has_variations: false,
  },
  {
    asin: "B09XBMXQ34",
    product_title:
      "Samsung 28L, Convection Microwave Oven with Curd Making(MC28A5013AK/TL, Black, 10 Yr warranty)",
    product_price: null,
    product_original_price: null,
    currency: null,
    product_star_rating: "4.2",
    product_num_ratings: 1641,
    product_url: "https://www.amazon.in/dp/B09XBMXQ34",
    product_photo:
      "https://m.media-amazon.com/images/I/710UhGWsb9L._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 4,
    product_minimum_offer_price: "₹12,400",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "1K+ bought in past month",
    delivery: null,
    has_variations: false,
  },
  {
    asin: "B0BMGD9Y2X",
    product_title:
      "LG 7 Kg, 5 Star, Direct Drive Technology, Steam Wash, 6 Motion DD, Smart Diagnosis, Fully-Automatic Front Load Washing Machine (FHM1207SDM, Allergy Care, In-Built Heater, Touch Panel, Middle Black)",
    product_price: "₹28,990",
    product_original_price: "₹43,990",
    currency: "INR",
    product_star_rating: "4.3",
    product_num_ratings: 2676,
    product_url: "https://www.amazon.in/dp/B0BMGD9Y2X",
    product_photo:
      "https://m.media-amazon.com/images/I/71msFUl565L._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹28,990",
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "2K+ bought in past month",
    delivery: "FREE delivery by Tue, 20 Aug, 7:00 am - 9:00 pm",
    has_variations: false,
  },
  {
    asin: "B09DD573SY",
    product_title:
      "LG 7 Kg 5 Star Wind Jet Dry Semi-Automatic Top Loading Washing Machine (P7020NGAZ, Dark Gray, Rat Away Feature)",
    product_price: "₹11,490",
    product_original_price: "₹16,090",
    currency: "INR",
    product_star_rating: "4.3",
    product_num_ratings: 5875,
    product_url: "https://www.amazon.in/dp/B09DD573SY",
    product_photo:
      "https://m.media-amazon.com/images/I/71o4XEEvEVL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 3,
    product_minimum_offer_price: "₹11,370",
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "1K+ bought in past month",
    delivery: "FREE delivery by Tue, 20 Aug, 7:00 am - 9:00 pm",
    has_variations: false,
  },
  {
    asin: "B0BTHLMS39",
    product_title:
      "Haier 190L 4-Star Direct Cool Single Door Refrigerator (HED-204DS-P, Dazzle Steel, 2024 Model)",
    product_price: "₹14,990",
    product_original_price: "₹20,990",
    currency: "INR",
    product_star_rating: "4.2",
    product_num_ratings: 1318,
    product_url: "https://www.amazon.in/dp/B0BTHLMS39",
    product_photo:
      "https://m.media-amazon.com/images/I/51fBESl4S1L._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹14,990",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "1K+ bought in past month",
    delivery: "FREE delivery by Tue, 20 Aug, 7:00 am - 9:00 pm",
    has_variations: false,
  },
  {
    asin: "B09R4RYCJ4",
    product_title:
      "Daikin 1.5 Ton 5 Star Inverter Split AC (Copper, PM 2.5 Filter, 2023 Model, MTKM50U, White)",
    product_price: "₹50,970",
    product_original_price: "₹75,990",
    currency: "INR",
    product_star_rating: "3.9",
    product_num_ratings: 2329,
    product_url: "https://www.amazon.in/dp/B09R4RYCJ4",
    product_photo:
      "https://m.media-amazon.com/images/I/61HuUBy7XIL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹50,970",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "500+ bought in past month",
    delivery: "Get it by Monday 26 August",
    has_variations: false,
  },
  {
    asin: "B016ZLKJSU",
    product_title:
      "IFB 30 L Convection Microwave Oven (30BRC2, Black, With Starter Kit), Standard",
    product_price: "₹14,390",
    product_original_price: "₹19,390",
    currency: "INR",
    product_star_rating: "4.3",
    product_num_ratings: 5765,
    product_url: "https://www.amazon.in/dp/B016ZLKJSU",
    product_photo:
      "https://m.media-amazon.com/images/I/71IWpC2j2kL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹14,390",
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "800+ bought in past month",
    delivery: "FREE delivery by Wed, 21 Aug, 7:00 am - 9:00 pm",
    has_variations: false,
  },
  {
    asin: "B0BB27FSW1",
    product_title:
      "Hindware Smart Appliances Nadia IN 60 cm 1500 m³/hr Stylish Filterless Auto-Clean Kitchen Chimney With Metallic Oil Collector, Motion Sensor &amp; Touch Control For Easy Operation (Curved Glass, Black)",
    product_price: "₹11,990",
    product_original_price: "₹27,990",
    currency: "INR",
    product_star_rating: "4",
    product_num_ratings: 939,
    product_url: "https://www.amazon.in/dp/B0BB27FSW1",
    product_photo:
      "https://m.media-amazon.com/images/I/61pbsyHbc-L._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹11,990",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "200+ bought in past month",
    delivery: "FREE delivery by Tue, 20 Aug, 7:00 am - 9:00 pm",
    has_variations: false,
  },
  {
    asin: "B09XBLS8XY",
    product_title:
      "Samsung 21 L, Convection Microwave Oven (CE73JD-B1/XTL, Black, Various Cooking Modes, Pre heat, Eco Mode, Power Defrost, Auto Cook, Wire Rack, Ceramic Enamel Cavity with 10 year warranty)",
    product_price: null,
    product_original_price: null,
    currency: null,
    product_star_rating: "4.3",
    product_num_ratings: 708,
    product_url: "https://www.amazon.in/dp/B09XBLS8XY",
    product_photo:
      "https://m.media-amazon.com/images/I/71oJR2snWCL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹11,200",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "600+ bought in past month",
    delivery: null,
    has_variations: false,
  },
  {
    asin: "B09Q94H46F",
    product_title:
      "LG 6.5 Kg, 5 Star, Direct Drive Technology, Steam Wash, 6 motion DD, Smart Diagnosis, Fully Automatic Front Load Washing Machine (FHM1065SDW, Allergy Care, In-Built Heater, Touch Panel, White)",
    product_price: "₹24,990",
    product_original_price: "₹37,990",
    currency: "INR",
    product_star_rating: "4.3",
    product_num_ratings: 5059,
    product_url: "https://www.amazon.in/dp/B09Q94H46F",
    product_photo:
      "https://m.media-amazon.com/images/I/713FPPHG-XL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹24,990",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "1K+ bought in past month",
    delivery: "FREE delivery by Tue, 20 Aug, 7:00 am - 9:00 pm",
    has_variations: false,
  },
  {
    asin: "B08G1S351Q",
    product_title:
      "Voltas Beko 14 Place Settings (DF14W, White, Inbuilt Heater)",
    product_price: "₹23,490",
    product_original_price: "₹29,990",
    currency: "INR",
    product_star_rating: "3.3",
    product_num_ratings: 382,
    product_url: "https://www.amazon.in/dp/B08G1S351Q",
    product_photo:
      "https://m.media-amazon.com/images/I/71kTPthG7oL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹23,490",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "50+ bought in past month",
    delivery: "FREE delivery by Tue, 20 Aug, 7:00 am - 9:00 pm",
    has_variations: true,
  },
  {
    asin: "B0BTHKW1T3",
    product_title:
      "Haier 185 L, 2 Star, Direct-Cool Single Door Refrigerator (HED-19TGG-N, Holy Leaf Glass, 2024 Model)",
    product_price: "₹15,190",
    product_original_price: "₹20,490",
    currency: "INR",
    product_star_rating: "4.2",
    product_num_ratings: 138,
    product_url: "https://www.amazon.in/dp/B0BTHKW1T3",
    product_photo:
      "https://m.media-amazon.com/images/I/61-P3CeDctL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 2,
    product_minimum_offer_price: "₹15,189",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "M.R.P: ",
    delivery: "FREE delivery by Tue, 20 Aug, 7:00 am - 9:00 pm",
    has_variations: false,
  },
  {
    asin: "B0BS9D9C2T",
    product_title:
      "Faber 60 Cm 1500 M³/Hr Autoclean Kitchen Chimney, 12Yr Warranty On Motor(2Yr Comprehensive), Autoclean Alarm, Mood L |Made In India(Hood Primus Plus Energy In Hcsc Bk 60,Touch&amp;Gesture Control,Black)",
    product_price: "₹14,600",
    product_original_price: "₹28,590",
    currency: "INR",
    product_star_rating: "4.6",
    product_num_ratings: 4054,
    product_url: "https://www.amazon.in/dp/B0BS9D9C2T",
    product_photo:
      "https://m.media-amazon.com/images/I/61zdMVHgDXL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹14,600",
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "900+ bought in past month",
    delivery: "FREE delivery by Tue, 20 Aug, 7:00 am - 9:00 pm",
    has_variations: false,
  },
  {
    asin: "B0BR5812CL",
    product_title:
      "Carrier 1.5 Ton 3 Star AI Flexicool Inverter Split AC (Copper, Convertible 4-in-1 Cooling,High Density Filter, Auto Cleanser, 2023 Model,ESTER Exi - CAI18ER3R32F0,White)",
    product_price: "₹38,990",
    product_original_price: "₹69,990",
    currency: "INR",
    product_star_rating: "3.7",
    product_num_ratings: 3115,
    product_url: "https://www.amazon.in/dp/B0BR5812CL",
    product_photo:
      "https://m.media-amazon.com/images/I/512J3gqzLuL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹38,990",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "50+ bought in past month",
    delivery: "Get it by Thursday 22 August",
    has_variations: false,
  },
  {
    asin: "B08GQDPJMP",
    product_title:
      "Hindware Smart Appliances Marvia 60 cm 1000 m³/hr Pyramid Kitchen Chimney With Elegant Look, Push Button Control, Efficient Dual LED Lamps &amp; Double Baffle Filter (Black)",
    product_price: "₹5,790",
    product_original_price: "₹13,490",
    currency: "INR",
    product_star_rating: "4",
    product_num_ratings: 499,
    product_url: "https://www.amazon.in/dp/B08GQDPJMP",
    product_photo:
      "https://m.media-amazon.com/images/I/61zIIo3EKXL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹5,790",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "200+ bought in past month",
    delivery: "FREE delivery by Tue, 20 Aug, 7:00 am - 9:00 pm",
    has_variations: false,
  },
  {
    asin: "B0BFFNNT5D",
    product_title:
      "Elica 60 cm 1200 m3/hr Filterless Autoclean Kitchen Chimney (FL 600 SLIM HAC MS NERO, Touch + Motion Sensor Control, Black)",
    product_price: "₹10,999",
    product_original_price: "₹24,990",
    currency: "INR",
    product_star_rating: "4.6",
    product_num_ratings: 1608,
    product_url: "https://www.amazon.in/dp/B0BFFNNT5D",
    product_photo:
      "https://m.media-amazon.com/images/I/61-NpR9KD7L._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹10,999",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "400+ bought in past month",
    delivery: "FREE delivery by Tue, 20 Aug, 7:00 am - 9:00 pm",
    has_variations: false,
  },
  {
    asin: "B08CKNVG3B",
    product_title:
      "Elica 60 cm 1200 m3/hr Filterless Autoclean Kitchen Chimney with 15 Years Warranty (WDFL 606 HAC LTW MS NERO, Touch + Motion Sensor Control, Black)",
    product_price: "₹12,490",
    product_original_price: "₹23,990",
    currency: "INR",
    product_star_rating: "4.5",
    product_num_ratings: 13057,
    product_url: "https://www.amazon.in/dp/B08CKNVG3B",
    product_photo:
      "https://m.media-amazon.com/images/I/61MMo3L63rL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹12,490",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "700+ bought in past month",
    delivery: "FREE delivery by Tue, 20 Aug, 7:00 am - 9:00 pm",
    has_variations: false,
  },
  {
    asin: "B0BK1GTTKC",
    product_title:
      "Daikin 1.8 Ton 3 Star Inverter Split AC (Copper, Anti Bacterial Filter, ATKL60UV16, White)",
    product_price: "₹49,990",
    product_original_price: "₹72,900",
    currency: "INR",
    product_star_rating: "3.5",
    product_num_ratings: 141,
    product_url: "https://www.amazon.in/dp/B0BK1GTTKC",
    product_photo:
      "https://m.media-amazon.com/images/I/416aYDOny1L._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹49,990",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "50+ bought in past month",
    delivery: "FREE delivery by Tue, 20 Aug, 7:00 am - 9:00 pm",
    has_variations: false,
  },
  {
    asin: "B0BTHLCK15",
    product_title:
      "Haier 165 L, 1 Star, Direct-Cool Single Door Refrigerator (HED-171RS-P, Red Steel, 2024 Model)",
    product_price: "₹11,190",
    product_original_price: "₹14,990",
    currency: "INR",
    product_star_rating: "3.9",
    product_num_ratings: 1947,
    product_url: "https://www.amazon.in/dp/B0BTHLCK15",
    product_photo:
      "https://m.media-amazon.com/images/I/51FJ-6IDORL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹11,190",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "700+ bought in past month",
    delivery: "FREE delivery by Tue, 20 Aug, 7:00 am - 9:00 pm",
    has_variations: true,
  },
  {
    asin: "B0BML9TRNJ",
    product_title:
      "Faber 60 Cm 1350 M³/Hr Slant, Filterless Auto Clean Chimney,12 Yr Warranty On Motor (2 Yr Comprehensive), Itailan Design, (HOOD BLISS FL SC AC BK 60, Touch &amp; Gesture Control, Black)",
    product_price: "₹21,470",
    product_original_price: "₹32,990",
    currency: "INR",
    product_star_rating: "4.4",
    product_num_ratings: 2460,
    product_url: "https://www.amazon.in/dp/B0BML9TRNJ",
    product_photo:
      "https://m.media-amazon.com/images/I/61O1HFoGrpL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹21,470",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "200+ bought in past month",
    delivery: "FREE delivery by Tue, 20 Aug, 7:00 am - 9:00 pm",
    has_variations: false,
  },
  {
    asin: "B0BT117FDS",
    product_title:
      "Blue Star 1.5 Ton 5 Star Convertible 5 in 1 Cooling Inverter Split Air Conditioner (IC518YNU, White)",
    product_price: "₹44,490",
    product_original_price: "₹73,000",
    currency: "INR",
    product_star_rating: "3.5",
    product_num_ratings: 1597,
    product_url: "https://www.amazon.in/dp/B0BT117FDS",
    product_photo:
      "https://m.media-amazon.com/images/I/61nF5ekaaPL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 5,
    product_minimum_offer_price: "₹43,650",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "M.R.P: ",
    delivery: "FREE delivery by Wed, 21 Aug, 7:00 am - 9:00 pm",
    has_variations: false,
  },
  {
    asin: "B00O21VEKI",
    product_title:
      "IFB 5.5 kg Front Load Fully-automatic Dryer (TURBO DRY,white,Inbuilt Heater, Allergy Free Technology",
    product_price: "₹19,490",
    product_original_price: "₹22,690",
    currency: "INR",
    product_star_rating: "3.9",
    product_num_ratings: 1124,
    product_url: "https://www.amazon.in/dp/B00O21VEKI",
    product_photo:
      "https://m.media-amazon.com/images/I/717opUxLU4L._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 3,
    product_minimum_offer_price: "₹19,290",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "200+ bought in past month",
    delivery: "FREE delivery by Tue, 20 Aug, 7:00 am - 9:00 pm",
    has_variations: false,
  },
];

export const AirConditioner = [
  {
    asin: "B0BK1KS6ZD",
    product_title:
      "Daikin 1.5 Ton 3 Star Inverter Split AC (Copper, PM 2.5 Filter, Triple Display, Dew Clean Technology, Coanda Airflow, 2023 Model, MTKL50U, White)",
    product_price: "₹36,990",
    product_original_price: "₹58,400",
    currency: "INR",
    product_star_rating: "3.7",
    product_num_ratings: 3199,
    product_url: "https://www.amazon.in/dp/B0BK1KS6ZD",
    product_photo:
      "https://m.media-amazon.com/images/I/61pzTsT7ZgL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹36,990",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "1K+ bought in past month",
    delivery: "FREE delivery by Wed, 21 Aug, 7:00 am - 9:00 pm",
    has_variations: false,
  },
  {
    asin: "B09R4SF5SP",
    product_title:
      "Daikin 0.8 Ton 3 Star, Fixed Speed Split AC (Copper, PM 2.5 Filter, 2022 Model, FTL28U, White)",
    product_price: "₹25,990",
    product_original_price: "₹37,400",
    currency: "INR",
    product_star_rating: "4",
    product_num_ratings: 3264,
    product_url: "https://www.amazon.in/dp/B09R4SF5SP",
    product_photo:
      "https://m.media-amazon.com/images/I/61mOVGinDdL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹25,990",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "600+ bought in past month",
    delivery: "FREE delivery by Wed, 21 Aug, 7:00 am - 9:00 pm",
    has_variations: false,
  },
  {
    asin: "B09R4RYCJ4",
    product_title:
      "Daikin 1.5 Ton 5 Star Inverter Split AC (Copper, PM 2.5 Filter, 2023 Model, MTKM50U, White)",
    product_price: "₹50,970",
    product_original_price: "₹75,990",
    currency: "INR",
    product_star_rating: "3.9",
    product_num_ratings: 2334,
    product_url: "https://www.amazon.in/dp/B09R4RYCJ4",
    product_photo:
      "https://m.media-amazon.com/images/I/61HuUBy7XIL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹50,970",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "400+ bought in past month",
    delivery: "Get it by Monday 26 August",
    has_variations: false,
  },
  {
    asin: "B0BK1GTTKC",
    product_title:
      "Daikin 1.8 Ton 3 Star Inverter Split AC (Copper, Anti Bacterial Filter, ATKL60UV16, White)",
    product_price: "₹49,990",
    product_original_price: "₹72,900",
    currency: "INR",
    product_star_rating: "3.5",
    product_num_ratings: 141,
    product_url: "https://www.amazon.in/dp/B0BK1GTTKC",
    product_photo:
      "https://m.media-amazon.com/images/I/416aYDOny1L._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹49,990",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "M.R.P: ",
    delivery: "FREE delivery by Wed, 21 Aug, 7:00 am - 9:00 pm",
    has_variations: false,
  },
  {
    asin: "B0BT117FDS",
    product_title:
      "Blue Star 1.5 Ton 5 Star Convertible 5 in 1 Cooling Inverter Split Air Conditioner (IC518YNU, White)",
    product_price: "₹44,490",
    product_original_price: "₹73,000",
    currency: "INR",
    product_star_rating: "3.5",
    product_num_ratings: 1599,
    product_url: "https://www.amazon.in/dp/B0BT117FDS",
    product_photo:
      "https://m.media-amazon.com/images/I/61nF5ekaaPL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 5,
    product_minimum_offer_price: "₹43,650",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "M.R.P: ",
    delivery: "FREE delivery by Wed, 21 Aug, 7:00 am - 9:00 pm",
    has_variations: false,
  },
  {
    asin: "B0BR5812CL",
    product_title:
      "Carrier 1.5 Ton 3 Star AI Flexicool Inverter Split AC (Copper, Convertible 4-in-1 Cooling,High Density Filter, Auto Cleanser, 2023 Model,ESTER Exi - CAI18ER3R32F0,White)",
    product_price: "₹38,990",
    product_original_price: "₹69,990",
    currency: "INR",
    product_star_rating: "3.7",
    product_num_ratings: 3122,
    product_url: "https://www.amazon.in/dp/B0BR5812CL",
    product_photo:
      "https://m.media-amazon.com/images/I/512J3gqzLuL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹38,990",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "50+ bought in past month",
    delivery: "Get it by Thursday 22 August",
    has_variations: false,
  },
  {
    asin: "B0BBFTT3YL",
    product_title:
      "Voltas 2 Ton 3 Star, Inverter Split AC(Copper, 4-in-1 Adjustable Mode, Anti-dust Filter, 2023 Model, 243V Vectra Elite, White)",
    product_price: "₹43,590",
    product_original_price: "₹79,990",
    currency: "INR",
    product_star_rating: "3.6",
    product_num_ratings: 165,
    product_url: "https://www.amazon.in/dp/B0BBFTT3YL",
    product_photo:
      "https://m.media-amazon.com/images/I/41e6oqY5-ZL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 3,
    product_minimum_offer_price: "₹43,290",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "M.R.P: ",
    delivery: "FREE delivery by Thu, 22 Aug, 7:00 am - 9:00 pm",
    has_variations: false,
  },
  {
    asin: "B0BQR2WMHX",
    product_title:
      "Voltas 1.5 Ton 3 Star, Fixed Speed Split AC (Copper, LED Display, Anti-dust Filter, 2023 Model, 183 Vectra Elegant, White)",
    product_price: "₹38,749",
    product_original_price: "₹67,990",
    currency: "INR",
    product_star_rating: "3.7",
    product_num_ratings: 30,
    product_url: "https://www.amazon.in/dp/B0BQR2WMHX",
    product_photo:
      "https://m.media-amazon.com/images/I/41LlSc9YsnL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 3,
    product_minimum_offer_price: "₹36,940",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "M.R.P: ",
    delivery: "Get it by Thursday 22 August",
    has_variations: false,
  },
  {
    asin: "B0BV1V4ND2",
    product_title:
      "Voltas 1 Ton 3 Star, Fixed Speed Window AC (Copper, Turbo Mode, 2023 Model, 123 Vectra Platina, White)",
    product_price: "₹28,649",
    product_original_price: "₹35,990",
    currency: "INR",
    product_star_rating: "3.8",
    product_num_ratings: 126,
    product_url: "https://www.amazon.in/dp/B0BV1V4ND2",
    product_photo:
      "https://m.media-amazon.com/images/I/81eJzRI-zHL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 8,
    product_minimum_offer_price: "₹26,960",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "50+ bought in past month",
    delivery: "Get it by Thursday 22 August",
    has_variations: false,
  },
  {
    asin: "B0BSJ7KZLJ",
    product_title:
      "Voltas 1.5 Ton 3 Star, Fixed Speed Window AC (Copper, Turbo Mode, 2023 Model, 183 Vectra Pearl, White)",
    product_price: "₹32,490",
    product_original_price: "₹59,990",
    currency: "INR",
    product_star_rating: "3.9",
    product_num_ratings: 2238,
    product_url: "https://www.amazon.in/dp/B0BSJ7KZLJ",
    product_photo:
      "https://m.media-amazon.com/images/I/61hrzDc3aTL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 10,
    product_minimum_offer_price: "₹30,450",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "100+ bought in past month",
    delivery: "Get it by Monday 26 August",
    has_variations: false,
  },
  {
    asin: "B0BQR2T346",
    product_title:
      "Voltas 1.5 Ton 5 Star, Inverter Split AC(Copper, 4-in-1 Adjustable Mode, Anti-dust Filter, 2023 Model, 185V Vectra Elegant,White)",
    product_price: "₹39,990",
    product_original_price: "₹75,990",
    currency: "INR",
    product_star_rating: "3.5",
    product_num_ratings: 1194,
    product_url: "https://www.amazon.in/dp/B0BQR2T346",
    product_photo:
      "https://m.media-amazon.com/images/I/51ayyOq4zeL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 2,
    product_minimum_offer_price: "₹38,990",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    product_availability: "Only 2 left in stock.",
    climate_pledge_friendly: false,
    sales_volume: "M.R.P: ",
    delivery:
      "FREE delivery by Wed, 21 Aug, 7:00 am - 9:00 pmOnly 2 left in stock.",
    has_variations: false,
  },
  {
    asin: "B0BTVRM525",
    product_title:
      "Hitachi 1.5 Ton 3 Star ice Clean Xpandable Plus Inverter Split AC (100% Copper, Dust Filter, 2024 Model, iZen 3400FXL, R32-RAS.G318PCBISF, Dual Gold)",
    product_price: "₹36,190",
    product_original_price: "₹63,100",
    currency: "INR",
    product_star_rating: "3.4",
    product_num_ratings: 75,
    product_url: "https://www.amazon.in/dp/B0BTVRM525",
    product_photo:
      "https://m.media-amazon.com/images/I/51qAUryQ5DL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹36,190",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "M.R.P: ",
    delivery: "Get it by Tomorrow, 9 pm",
    has_variations: false,
  },
  {
    asin: "B09R4RXLT4",
    product_title:
      "Daikin 1 Ton 5 Star Inverter Split AC (Copper, PM 2.5 Filter, 2022 Model, MTKM35U, White)",
    product_price: "₹38,990",
    product_original_price: "₹55,500",
    currency: "INR",
    product_star_rating: "3.9",
    product_num_ratings: 679,
    product_url: "https://www.amazon.in/dp/B09R4RXLT4",
    product_photo:
      "https://m.media-amazon.com/images/I/61HuUBy7XIL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹38,990",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "100+ bought in past month",
    delivery: "FREE delivery by Wed, 21 Aug, 7:00 am - 9:00 pm",
    has_variations: false,
  },
  {
    asin: "B0BBFWM5F9",
    product_title:
      "Voltas 2 Ton 5 Star, Inverter Split AC(Copper,4-in-1 Adjustable Mode, Anti-dust Filter, 2023 Model, 245V Vectra Plus, White)",
    product_price: "₹57,499",
    product_original_price: "₹93,900",
    currency: "INR",
    product_star_rating: "3.8",
    product_num_ratings: 209,
    product_url: "https://www.amazon.in/dp/B0BBFWM5F9",
    product_photo:
      "https://m.media-amazon.com/images/I/41M7ocgxanL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 9,
    product_minimum_offer_price: "₹56,490",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "M.R.P: ",
    delivery: "Get it by Thursday 22 August",
    has_variations: false,
  },
  {
    asin: "B09R4QLDWK",
    product_title:
      "Daikin 1.5 Ton 3 Star Fixed Speed Split AC (Copper, PM 2.5 Filter, 2022 Model, FTL50U, White)",
    product_price: "₹39,990",
    product_original_price: "₹55,600",
    currency: "INR",
    product_star_rating: "4",
    product_num_ratings: 656,
    product_url: "https://www.amazon.in/dp/B09R4QLDWK",
    product_photo:
      "https://m.media-amazon.com/images/I/410ih0eEMfL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 10,
    product_minimum_offer_price: "₹39,810",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "M.R.P: ",
    delivery: "FREE delivery by Wed, 21 Aug, 7:00 am - 9:00 pm",
    has_variations: false,
  },
  {
    asin: "B0BRJ5X198",
    product_title:
      "Panasonic 1 Ton 3 Star Wi-Fi Inverter Smart Split AC (Copper Condenser, 7 in 1 Convertible with additional AI Mode, PM 0.1 Air Purification Filter, CS/CU-SU12YKYWA,2023 Model, White)",
    product_price: "₹36,990",
    product_original_price: "₹54,990",
    currency: "INR",
    product_star_rating: "3.8",
    product_num_ratings: 855,
    product_url: "https://www.amazon.in/dp/B0BRJ5X198",
    product_photo:
      "https://m.media-amazon.com/images/I/61bfA4GFKJL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹36,990",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    product_availability: "Only 1 left in stock.",
    climate_pledge_friendly: false,
    sales_volume: "M.R.P: ",
    delivery: "Get it by Monday 26 AugustOnly 1 left in stock.",
    has_variations: false,
  },
  {
    asin: "B094752MJ5",
    product_title:
      "Cruise 1.5 Ton 3 Star Turbo Inverter Split AC with 7-Stage Air Filtration (100% Copper, Convertible 4-in-1, PM 2.5 Filter, 2024 Model, CWCVBH-VQ1W183, White)",
    product_price: "₹37,089",
    product_original_price: "₹51,900",
    currency: "INR",
    product_star_rating: "4",
    product_num_ratings: 1394,
    product_url: "https://www.amazon.in/dp/B094752MJ5",
    product_photo:
      "https://m.media-amazon.com/images/I/518DOj7n0yL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹37,089",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "M.R.P: ",
    delivery: "Get it by Thursday 22 August",
    has_variations: false,
  },
  {
    asin: "B09RFZVLZH",
    product_title:
      "Blue Star 4 in 1 Convertible 2 Ton 3 Star Inverter Split Air Conditioner with Dust Filter (Copper Condenser, IA324YNU)",
    product_price: "₹50,990",
    product_original_price: "₹84,990",
    currency: "INR",
    product_star_rating: "3.7",
    product_num_ratings: 91,
    product_url: "https://www.amazon.in/dp/B09RFZVLZH",
    product_photo:
      "https://m.media-amazon.com/images/I/41K8zEvR84L._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 3,
    product_minimum_offer_price: "₹49,990",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "M.R.P: ",
    delivery: "Get it by Monday 26 August",
    has_variations: false,
  },
  {
    asin: "B0BBFW3G8M",
    product_title:
      "Voltas 1.5 Ton 3 Star, Inverter Split AC(Copper, 4 in 1 Adjustable Cooling, Anti-dust Filter, 2023 Model, 183V Vectra Platina, White)",
    product_price: "₹32,349",
    product_original_price: "₹64,990",
    currency: "INR",
    product_star_rating: "3.5",
    product_num_ratings: 286,
    product_url: "https://www.amazon.in/dp/B0BBFW3G8M",
    product_photo:
      "https://m.media-amazon.com/images/I/41TuyxwZ9mL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹32,349",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "M.R.P: ",
    delivery: "Get it by Thursday 22 August",
    has_variations: false,
  },
  {
    asin: "B0BR58HRD2",
    product_title:
      "Carrier 1 Ton 3 Star AI Flexicool Inverter Split AC (Copper, Convertible 4-in-1 Cooling,Dual Filtration with HD &amp; PM 2.5 Filter, Auto Cleanser, 2023 Model,ESTER Exi - CAI12ER3R33F0,White)",
    product_price: "₹29,999",
    product_original_price: "₹56,990",
    currency: "INR",
    product_star_rating: "3.8",
    product_num_ratings: 1666,
    product_url: "https://www.amazon.in/dp/B0BR58HRD2",
    product_photo:
      "https://m.media-amazon.com/images/I/512J3gqzLuL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹29,999",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "M.R.P: ",
    delivery: null,
    has_variations: false,
  },
  {
    asin: "B08Z47LWL4",
    product_title:
      "Hitachi 1.5 Ton 5 Star Inverter Split AC (Copper, Dust Filter, 2021 Model, RSRG518HEEA, White), Free 1 Year Extended warranty",
    product_price: "₹44,490",
    product_original_price: "₹75,990",
    currency: "INR",
    product_star_rating: "3.8",
    product_num_ratings: 905,
    product_url: "https://www.amazon.in/dp/B08Z47LWL4",
    product_photo:
      "https://m.media-amazon.com/images/I/51gom9JKrNS._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹44,490",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "M.R.P: ",
    delivery: "Get it by Monday 26 August",
    has_variations: false,
  },
  {
    asin: "B09W5K2L16",
    product_title:
      "Voltas Split Air Conditioner SAC 185V CAZZ, White, (4503222)",
    product_price: "₹41,990",
    product_original_price: "₹71,990",
    currency: "INR",
    product_star_rating: "3.1",
    product_num_ratings: 6,
    product_url: "https://www.amazon.in/dp/B09W5K2L16",
    product_photo:
      "https://m.media-amazon.com/images/I/61a-F8WxWOL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹41,990",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "M.R.P: ",
    delivery: "FREE delivery by Wed, 21 Aug, 7:00 am - 9:00 pm",
    has_variations: false,
  },
  {
    asin: "B0BW9LFNRM",
    product_title:
      "Blue Star 1 Ton 5 Star Convertible 5 in 1 Cooling Inverter Split AC (Copper, Multi Sensors, Dust Filters, Smart Ready, Blue Fins, Self Diagnosis, 2023Model, IC512YNU,White)",
    product_price: "₹39,990",
    product_original_price: "₹75,990",
    currency: "INR",
    product_star_rating: "3.9",
    product_num_ratings: 3382,
    product_url: "https://www.amazon.in/dp/B0BW9LFNRM",
    product_photo:
      "https://m.media-amazon.com/images/I/61nF5ekaaPL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹39,990",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "M.R.P: ",
    delivery: "Get it by Monday 26 August",
    has_variations: false,
  },
  {
    asin: "B0B67S3TXP",
    product_title:
      "Carrier 2 Ton 3 Star AI Flexicool Inverter Split AC (Copper, Convertible 4-in-1 Cooling,Dual Filtration, Auto Cleanser, 2023 Model,ESTER Exi - CAI24ES3R32F0,White)",
    product_price: "₹49,880",
    product_original_price: "₹84,990",
    currency: "INR",
    product_star_rating: "3.7",
    product_num_ratings: 196,
    product_url: "https://www.amazon.in/dp/B0B67S3TXP",
    product_photo:
      "https://m.media-amazon.com/images/I/51joCIotxEL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹49,880",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "M.R.P: ",
    delivery: "Get it by Monday 26 August",
    has_variations: false,
  },
];

export const microwave = [
  {
    asin: "B06XKC8S71",
    product_title:
      "LG 28 L Convection Microwave Oven (MC2846BV, Black, Quartz Heater)",
    product_price: null,
    product_original_price: null,
    currency: null,
    product_star_rating: "4.4",
    product_num_ratings: 884,
    product_url: "https://www.amazon.in/dp/B06XKC8S71",
    product_photo:
      "https://m.media-amazon.com/images/I/71gEAVX6ojL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: null,
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "1K+ bought in past month",
    delivery: "Currently unavailable.",
    has_variations: false,
  },
  {
    asin: "B07MC84QPL",
    product_title:
      "LG 20 L Solo Microwave Oven (MS2043BP, Black, With Health Plus Menu &amp; Steam Clean)",
    product_price: "₹6,990",
    product_original_price: "₹8,199",
    currency: "INR",
    product_star_rating: "4.2",
    product_num_ratings: 2892,
    product_url: "https://www.amazon.in/dp/B07MC84QPL",
    product_photo:
      "https://m.media-amazon.com/images/I/713c8U4U8QL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹6,990",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "800+ bought in past month",
    delivery: "FREE delivery by Wed, 21 Aug, 7:00 am - 9:00 pm",
    has_variations: false,
  },
  {
    asin: "B08CL8XF75",
    product_title:
      "Panasonic 20L Solo Microwave Oven (NN-ST26JMFDG, Silver, 51 Auto Menus)",
    product_price: "₹6,290",
    product_original_price: "₹7,490",
    currency: "INR",
    product_star_rating: "4.3",
    product_num_ratings: 5882,
    product_url: "https://www.amazon.in/dp/B08CL8XF75",
    product_photo:
      "https://m.media-amazon.com/images/I/61Md+j4GC3L._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹6,290",
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "2K+ bought in past month",
    delivery: "FREE delivery by Wed, 21 Aug, 7:00 am - 9:00 pm",
    has_variations: false,
  },
  {
    asin: "B08DYCWC9R",
    product_title: "Panasonic 20L Solo Microwave Oven (NN-SM25JBFDG,Black)",
    product_price: "₹5,690",
    product_original_price: "₹6,790",
    currency: "INR",
    product_star_rating: "4.3",
    product_num_ratings: 3274,
    product_url: "https://www.amazon.in/dp/B08DYCWC9R",
    product_photo:
      "https://m.media-amazon.com/images/I/618hSd40v6L._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹5,690",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "1K+ bought in past month",
    delivery: "FREE delivery by Wed, 21 Aug, 7:00 am - 9:00 pm",
    has_variations: false,
  },
  {
    asin: "B09XBMXQ34",
    product_title:
      "Samsung 28L, Convection Microwave Oven with Curd Making(MC28A5013AK/TL, Black, 10 Yr warranty)",
    product_price: "₹12,490",
    product_original_price: "₹15,590",
    currency: "INR",
    product_star_rating: "4.2",
    product_num_ratings: 1645,
    product_url: "https://www.amazon.in/dp/B09XBMXQ34",
    product_photo:
      "https://m.media-amazon.com/images/I/710UhGWsb9L._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹12,490",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "1K+ bought in past month",
    delivery: "FREE delivery by Wed, 21 Aug, 7:00 am - 9:00 pm",
    has_variations: false,
  },
  {
    asin: "B09PV84DMX",
    product_title:
      "Samsung 23 L Solo Microwave Oven (MS23A3513AK/TL, Black, Auto Cook Programs, Child Safety Lock, Memory Feature, Deodorization, Ceramic Enamel Cavity with 10 year warranty)",
    product_price: "₹7,490",
    product_original_price: "₹8,290",
    currency: "INR",
    product_star_rating: "4.3",
    product_num_ratings: 702,
    product_url: "https://www.amazon.in/dp/B09PV84DMX",
    product_photo:
      "https://m.media-amazon.com/images/I/61dmsjEJCFL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹7,490",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "700+ bought in past month",
    delivery: null,
    has_variations: false,
  },
  {
    asin: "B016ZLKJSU",
    product_title:
      "IFB 30 L Convection Microwave Oven (30BRC2, Black, With Starter Kit), Standard",
    product_price: "₹15,290",
    product_original_price: "₹19,390",
    currency: "INR",
    product_star_rating: "4.3",
    product_num_ratings: 5767,
    product_url: "https://www.amazon.in/dp/B016ZLKJSU",
    product_photo:
      "https://m.media-amazon.com/images/I/71IWpC2j2kL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹15,290",
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "800+ bought in past month",
    delivery: "FREE delivery by Wed, 21 Aug, 7:00 am - 9:00 pm",
    has_variations: false,
  },
  {
    asin: "B01LWE0QJK",
    product_title:
      "LG 32 L Convection Microwave Oven (MC3286BRUM, Black, 360° Motorised Rotisserie &amp; Diet Fry)",
    product_price: "₹17,990",
    product_original_price: "₹23,999",
    currency: "INR",
    product_star_rating: "4.4",
    product_num_ratings: 2468,
    product_url: "https://www.amazon.in/dp/B01LWE0QJK",
    product_photo:
      "https://m.media-amazon.com/images/I/71ajlK79v7L._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹17,990",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "200+ bought in past month",
    delivery: "FREE delivery by Wed, 21 Aug, 7:00 am - 9:00 pm",
    has_variations: false,
  },
  {
    asin: "B00R5QNW8E",
    product_title: "LG 20 L Grill Microwave Oven (MH2044DB, Black)",
    product_price: "₹7,889",
    product_original_price: "₹10,199",
    currency: "INR",
    product_star_rating: "4.2",
    product_num_ratings: 826,
    product_url: "https://www.amazon.in/dp/B00R5QNW8E",
    product_photo:
      "https://m.media-amazon.com/images/I/71VXDchzJrL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹7,889",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "300+ bought in past month",
    delivery: "FREE delivery by Wed, 21 Aug, 7:00 am - 9:00 pm",
    has_variations: false,
  },
  {
    asin: "B09BKZCSXP",
    product_title:
      "Voltas Beko, A Tata Product 20L, 700W smart solo Microwave oven (MS20MPW10, White)",
    product_price: null,
    product_original_price: null,
    currency: null,
    product_star_rating: "4.1",
    product_num_ratings: 137,
    product_url: "https://www.amazon.in/dp/B09BKZCSXP",
    product_photo:
      "https://m.media-amazon.com/images/I/51DenBugfAL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹6,850",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "100+ bought in past month",
    delivery: null,
    has_variations: false,
  },
  {
    asin: "B00KPSSPZY",
    product_title:
      "Panasonic 23L Convection Microwave Oven(NN-CT353BFDG,Black Mirror, 360° Heat Wrap, Magic Grill)",
    product_price: "₹10,290",
    product_original_price: "₹14,990",
    currency: "INR",
    product_star_rating: "4.5",
    product_num_ratings: 1940,
    product_url: "https://www.amazon.in/dp/B00KPSSPZY",
    product_photo:
      "https://m.media-amazon.com/images/I/61Wt846zGOL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹10,290",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "600+ bought in past month",
    delivery: "FREE delivery by Wed, 21 Aug, 7:00 am - 9:00 pm",
    has_variations: false,
  },
  {
    asin: "B06XK8RY1Q",
    product_title:
      "LG 21 L Convection Microwave Oven (MC2146BV, Black, With Heathplus menu &amp; Quartz Heater)",
    product_price: "₹12,542.48",
    product_original_price: "₹14,490",
    currency: "INR",
    product_star_rating: "4.4",
    product_num_ratings: 331,
    product_url: "https://www.amazon.in/dp/B06XK8RY1Q",
    product_photo:
      "https://m.media-amazon.com/images/I/71aWwkETYaL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹12,542.48",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "200+ bought in past month",
    delivery: "Get it by Thursday 22 August",
    has_variations: false,
  },
  {
    asin: "B09XBLS8XY",
    product_title:
      "Samsung 21 L, Convection Microwave Oven (CE73JD-B1/XTL, Black, Various Cooking Modes, Pre heat, Eco Mode, Power Defrost, Auto Cook, Wire Rack, Ceramic Enamel Cavity with 10 year warranty)",
    product_price: null,
    product_original_price: null,
    currency: null,
    product_star_rating: "4.3",
    product_num_ratings: 709,
    product_url: "https://www.amazon.in/dp/B09XBLS8XY",
    product_photo:
      "https://m.media-amazon.com/images/I/71oJR2snWCL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹11,200",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "600+ bought in past month",
    delivery: null,
    has_variations: false,
  },
  {
    asin: "B072KZ373J",
    product_title: "Bajaj MTBX 2016 20L Grill Microwave Oven, Black",
    product_price: "₹5,799",
    product_original_price: "₹7,775",
    currency: "INR",
    product_star_rating: "4.3",
    product_num_ratings: 2567,
    product_url: "https://www.amazon.in/dp/B072KZ373J",
    product_photo:
      "https://m.media-amazon.com/images/I/71ITInjy-FL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹5,799",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "50+ bought in past month",
    delivery: "FREE delivery by Wed, 21 Aug, 7:00 am - 9:00 pm",
    has_variations: false,
  },
  {
    asin: "B016XZP3DY",
    product_title:
      "IFB 30 L Convection Microwave Oven (30FRC2, Floral Pattern) (Black), STANDARD",
    product_price: "₹16,199",
    product_original_price: "₹20,990",
    currency: "INR",
    product_star_rating: "4.3",
    product_num_ratings: 3123,
    product_url: "https://www.amazon.in/dp/B016XZP3DY",
    product_photo:
      "https://m.media-amazon.com/images/I/717XfVZ0iOL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 2,
    product_minimum_offer_price: "₹15,280",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "100+ bought in past month",
    delivery: "FREE delivery by Wed, 21 Aug, 7:00 am - 9:00 pm",
    has_variations: false,
  },
  {
    asin: "B085V1JD27",
    product_title: "IFB 25 L Solo Microwave Oven (25PM2S, IFBJ0, Silver)",
    product_price: "₹7,640",
    product_original_price: "₹9,490",
    currency: "INR",
    product_star_rating: "4.3",
    product_num_ratings: 1433,
    product_url: "https://www.amazon.in/dp/B085V1JD27",
    product_photo:
      "https://m.media-amazon.com/images/I/819s6STd6pL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹7,640",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "100+ bought in past month",
    delivery: "FREE delivery by Wed, 21 Aug, 7:00 am - 9:00 pm",
    has_variations: false,
  },
  {
    asin: "B00F15AFPY",
    product_title: "Bajaj 1701 MT 17L Solo Microwave Oven, White",
    product_price: null,
    product_original_price: null,
    currency: null,
    product_star_rating: "4.4",
    product_num_ratings: 5992,
    product_url: "https://www.amazon.in/dp/B00F15AFPY",
    product_photo:
      "https://m.media-amazon.com/images/I/61pDIEAuU1L._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹8,288",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "No featured offers available",
    delivery: null,
    has_variations: false,
  },
  {
    asin: "B015AAV3PA",
    product_title: "IFB 20 L Grill Microwave Oven (20PG4S, Black/ Silver)",
    product_price: "₹8,890",
    product_original_price: "₹10,590",
    currency: "INR",
    product_star_rating: "4.3",
    product_num_ratings: 621,
    product_url: "https://www.amazon.in/dp/B015AAV3PA",
    product_photo:
      "https://m.media-amazon.com/images/I/81bTlOxnLlL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹8,890",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "50+ bought in past month",
    delivery: "FREE delivery by Wed, 21 Aug, 7:00 am - 9:00 pm",
    has_variations: false,
  },
  {
    asin: "B00A7PGI18",
    product_title:
      "IFB 20 L Convection Microwave Oven (20SC2, Metallic Silver, With Starter Kit), STANDARD",
    product_price: "₹12,027.51",
    product_original_price: "₹14,990",
    currency: "INR",
    product_star_rating: "4.3",
    product_num_ratings: 5118,
    product_url: "https://www.amazon.in/dp/B00A7PGI18",
    product_photo:
      "https://m.media-amazon.com/images/I/71W-OAGCL0L._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹12,000",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    product_availability: "Only 1 left in stock.",
    climate_pledge_friendly: false,
    sales_volume: "50+ bought in past month",
    delivery: "Get it by Thursday 22 AugustOnly 1 left in stock.",
    has_variations: false,
  },
  {
    asin: "B08NQJVWGQ",
    product_title:
      "IFB 30 L Convection Microwave Oven with Oil Free Cooking (30BC5, Black, With Starter Kit)",
    product_price: "₹14,490",
    product_original_price: "₹17,890",
    currency: "INR",
    product_star_rating: "4.2",
    product_num_ratings: 384,
    product_url: "https://www.amazon.in/dp/B08NQJVWGQ",
    product_photo:
      "https://m.media-amazon.com/images/I/71ez-kobuhL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹14,490",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "50+ bought in past month",
    delivery: "FREE delivery by Wed, 21 Aug, 7:00 am - 9:00 pm",
    has_variations: false,
  },
  {
    asin: "B09HMGHFB6",
    product_title: "IFB 20 Litre Solo Microwave Oven (20PM-MEC2) White",
    product_price: null,
    product_original_price: null,
    currency: null,
    product_star_rating: "4.4",
    product_num_ratings: 347,
    product_url: "https://www.amazon.in/dp/B09HMGHFB6",
    product_photo:
      "https://m.media-amazon.com/images/I/611Q8uHxkFL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 3,
    product_minimum_offer_price: "₹6,499",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "No featured offers available",
    delivery: null,
    has_variations: false,
  },
  {
    asin: "B01N4WJ6Y1",
    product_title: "Haier 23 L Convection Microwave Oven (HIL2301CSSH, Silver)",
    product_price: "₹9,490",
    product_original_price: "₹13,500",
    currency: "INR",
    product_star_rating: "4.2",
    product_num_ratings: 1018,
    product_url: "https://www.amazon.in/dp/B01N4WJ6Y1",
    product_photo:
      "https://m.media-amazon.com/images/I/61byLAW0M9L._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹9,490",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "M.R.P: ",
    delivery: "FREE delivery by Wed, 21 Aug, 7:00 am - 9:00 pm",
    has_variations: false,
  },
  {
    asin: "B07MC84GZH",
    product_title: "LG 28 L Convection Microwave Oven (MC2846BG, Black)",
    product_price: "₹14,840.10",
    product_original_price: "₹19,999",
    currency: "INR",
    product_star_rating: "4.4",
    product_num_ratings: 2343,
    product_url: "https://www.amazon.in/dp/B07MC84GZH",
    product_photo:
      "https://m.media-amazon.com/images/I/61xM+QwcTzL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹14,840.10",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "M.R.P: ",
    delivery: "Get it by Thursday 22 August",
    has_variations: false,
  },
  {
    asin: "B09M7DH9LJ",
    product_title:
      "LG 28 L Charcoal Convection Microwave Oven (MJ2887BFUM, Black, with 360° Motorised Rotisserie &amp; Charcoal Lighting Heater with 10 years warranty)",
    product_price: null,
    product_original_price: null,
    currency: null,
    product_star_rating: "4.3",
    product_num_ratings: 251,
    product_url: "https://www.amazon.in/dp/B09M7DH9LJ",
    product_photo:
      "https://m.media-amazon.com/images/I/71o2y8SKPCL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 2,
    product_minimum_offer_price: "₹21,000",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "No featured offers available",
    delivery: null,
    has_variations: false,
  },
];

export const Refrigerators = [
  {
    asin: "B0BTHLMS39",
    product_title:
      "Haier 190L 4-Star Direct Cool Single Door Refrigerator (HED-204DS-P, Dazzle Steel, 2024 Model)",
    product_price: "₹14,990",
    product_original_price: "₹20,990",
    currency: "INR",
    product_star_rating: "4.1",
    product_num_ratings: 1324,
    product_url: "https://www.amazon.in/dp/B0BTHLMS39",
    product_photo:
      "https://m.media-amazon.com/images/I/51fBESl4S1L._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹14,990",
    is_best_seller: false,
    is_amazon_choice: true,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "1K+ bought in past month",
    delivery: "FREE delivery by Wed, 21 Aug, 7:00 am - 8:00 pm",
    has_variations: false,
  },
  {
    asin: "B0BTHKW1T3",
    product_title:
      "Haier 185 L, 2 Star, Direct-Cool Single Door Refrigerator (HED-19TGG-N, Holy Leaf Glass, 2024 Model)",
    product_price: "₹15,190",
    product_original_price: "₹20,490",
    currency: "INR",
    product_star_rating: "4.2",
    product_num_ratings: 139,
    product_url: "https://www.amazon.in/dp/B0BTHKW1T3",
    product_photo:
      "https://m.media-amazon.com/images/I/61-P3CeDctL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 2,
    product_minimum_offer_price: "₹15,189",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "M.R.P: ",
    delivery: "FREE delivery by Wed, 21 Aug, 7:00 am - 9:00 pm",
    has_variations: false,
  },
  {
    asin: "B078YHT1FR",
    product_title:
      "Whirlpool 240 L Frost Free Triple-Door Refrigerator(FP 263D Protton Roy, Alpha Steel)",
    product_price: "₹25,300",
    product_original_price: "₹35,900",
    currency: "INR",
    product_star_rating: "4",
    product_num_ratings: 4709,
    product_url: "https://www.amazon.in/dp/B078YHT1FR",
    product_photo:
      "https://m.media-amazon.com/images/I/61+Ae1GP9GL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 3,
    product_minimum_offer_price: "₹25,210",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "50+ bought in past month",
    delivery: "Get it by Tomorrow, 9 pm",
    has_variations: false,
  },
  {
    asin: "B0BTHLCK15",
    product_title:
      "Haier 165 L, 1 Star, Direct-Cool Single Door Refrigerator (HED-171RS-P, Red Steel, 2024 Model)",
    product_price: "₹11,190",
    product_original_price: "₹14,990",
    currency: "INR",
    product_star_rating: "3.9",
    product_num_ratings: 1949,
    product_url: "https://www.amazon.in/dp/B0BTHLCK15",
    product_photo:
      "https://m.media-amazon.com/images/I/51FJ-6IDORL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹11,190",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "700+ bought in past month",
    delivery: "FREE delivery by Wed, 21 Aug, 7:00 am - 8:00 pm",
    has_variations: true,
  },
  {
    asin: "B09ZV9FP8M",
    product_title:
      "Toshiba 349L 2 Star Frost Free Inverter Double Door Refrigirator (GR-RB423WE-PMI(37, Satin Grey, Bottom Freezer, 2022 Model)",
    product_price: "₹39,981",
    product_original_price: "₹60,990",
    currency: "INR",
    product_star_rating: "5",
    product_num_ratings: 1,
    product_url: "https://www.amazon.in/dp/B09ZV9FP8M",
    product_photo:
      "https://m.media-amazon.com/images/I/51nouuhVkDL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹39,981",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "M.R.P: ",
    delivery: "FREE delivery by Wed, 21 Aug, 7:00 am - 9:00 pm",
    has_variations: false,
  },
  {
    asin: "B0BC44VSP3",
    product_title:
      "Godrej 234 L 2 Star Inverter, 24 Days Farm Freshness Frost Free Double Door Refrigerator Appliance(RT EONALPHA 250B 25 RI JD WN, Jade Wine)",
    product_price: null,
    product_original_price: null,
    currency: null,
    product_star_rating: "3.5",
    product_num_ratings: 44,
    product_url: "https://www.amazon.in/dp/B0BC44VSP3",
    product_photo:
      "https://m.media-amazon.com/images/I/614GVkQ3M3L._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹23,800",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "No featured offers available",
    delivery: null,
    has_variations: false,
  },
  {
    asin: "B0BTHMX9MY",
    product_title:
      "Haier 190 L 3 Star Direct Cool Single Door Refrigerator Appliance (2023 Model, HED-203RFB-P, Red Opal, Base Stand with Drawer)",
    product_price: "₹15,990",
    product_original_price: "₹22,990",
    currency: "INR",
    product_star_rating: "4",
    product_num_ratings: 98,
    product_url: "https://www.amazon.in/dp/B0BTHMX9MY",
    product_photo:
      "https://m.media-amazon.com/images/I/813tir2PKlL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹15,990",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "M.R.P: ",
    delivery: null,
    has_variations: false,
  },
  {
    asin: "B0B8ZQKLSY",
    product_title:
      "Haier 278 L 3 Star Double Door Frost Free Refrigerator Appliance, Twin Inverter Technology (HEF-27TMS, Moon Silver,Convertible, 2022 Model)",
    product_price: null,
    product_original_price: null,
    currency: null,
    product_star_rating: "3.8",
    product_num_ratings: 50,
    product_url: "https://www.amazon.in/dp/B0B8ZQKLSY",
    product_photo:
      "https://m.media-amazon.com/images/I/41dexdLzziL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹29,500",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "No featured offers available",
    delivery: null,
    has_variations: false,
  },
];

export const WashingMachine = [
  {
    asin: "B09DD573SY",
    product_title:
      "LG 7 Kg 5 Star Wind Jet Dry Semi-Automatic Top Loading Washing Machine (P7020NGAZ, Dark Gray, Rat Away Feature)",
    product_price: "₹11,490",
    product_original_price: "₹16,090",
    currency: "INR",
    product_star_rating: "4.3",
    product_num_ratings: 5884,
    product_url: "https://www.amazon.in/dp/B09DD573SY",
    product_photo:
      "https://m.media-amazon.com/images/I/71o4XEEvEVL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 3,
    product_minimum_offer_price: "₹11,370",
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "1K+ bought in past month",
    delivery: "FREE delivery by Wed, 21 Aug, 7:00 am - 8:00 pm",
    has_variations: false,
  },
  {
    asin: "B0BMGD9Y2X",
    product_title:
      "LG 7 Kg, 5 Star, Direct Drive Technology, Steam Wash, 6 Motion DD, Smart Diagnosis, Fully-Automatic Front Load Washing Machine (FHM1207SDM, Allergy Care, In-Built Heater, Touch Panel, Middle Black)",
    product_price: "₹28,990",
    product_original_price: "₹43,990",
    currency: "INR",
    product_star_rating: "4.3",
    product_num_ratings: 2683,
    product_url: "https://www.amazon.in/dp/B0BMGD9Y2X",
    product_photo:
      "https://m.media-amazon.com/images/I/71msFUl565L._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹28,990",
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "2K+ bought in past month",
    delivery: "FREE delivery by Wed, 21 Aug, 7:00 am - 9:00 pm",
    has_variations: false,
  },
  {
    asin: "B09Q94H46F",
    product_title:
      "LG 6.5 Kg, 5 Star, Direct Drive Technology, Steam Wash, 6 motion DD, Smart Diagnosis, Fully Automatic Front Load Washing Machine (FHM1065SDW, Allergy Care, In-Built Heater, Touch Panel, White)",
    product_price: "₹24,990",
    product_original_price: "₹37,990",
    currency: "INR",
    product_star_rating: "4.3",
    product_num_ratings: 5072,
    product_url: "https://www.amazon.in/dp/B09Q94H46F",
    product_photo:
      "https://m.media-amazon.com/images/I/713FPPHG-XL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹24,990",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "900+ bought in past month",
    delivery: "FREE delivery by Wed, 21 Aug, 7:00 am - 9:00 pm",
    has_variations: false,
  },
  {
    asin: "B00O21VEKI",
    product_title:
      "IFB 5.5 kg Front Load Fully-automatic Dryer (TURBO DRY,white,Inbuilt Heater, Allergy Free Technology",
    product_price: "₹20,790",
    product_original_price: "₹22,690",
    currency: "INR",
    product_star_rating: "3.9",
    product_num_ratings: 1124,
    product_url: "https://www.amazon.in/dp/B00O21VEKI",
    product_photo:
      "https://m.media-amazon.com/images/I/717opUxLU4L._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 3,
    product_minimum_offer_price: "₹19,290",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "200+ bought in past month",
    delivery: "FREE delivery by Wed, 21 Aug, 7:00 am - 9:00 pm",
    has_variations: false,
  },
  {
    asin: "B08ZJHJ5DJ",
    product_title:
      "Haier 7 Kg 5 star Fully Automatic Top Loading Washing Machine HWM70-AE, Titanium Grey, 2024, Oceanus Wave Drum,Near Zero Pressure)",
    product_price: "₹14,490",
    product_original_price: "₹14,990",
    currency: "INR",
    product_star_rating: "4.2",
    product_num_ratings: 1134,
    product_url: "https://www.amazon.in/dp/B08ZJHJ5DJ",
    product_photo:
      "https://m.media-amazon.com/images/I/61rD2AEWUrL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹14,490",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "300+ bought in past month",
    delivery: "FREE delivery by Wed, 21 Aug, 7:00 am - 9:00 pm",
    has_variations: false,
  },
  {
    asin: "B0BH87KJ8K",
    product_title:
      "IFB 8.0 Kg Fully-Automatic Top Loading Washing Machine (TL-SBRS 8.0 KG Aqua, Brown, 2X Power Steam, 4 Years Comprehensive Warranty)",
    product_price: "₹27,990",
    product_original_price: "₹32,950",
    currency: "INR",
    product_star_rating: "4",
    product_num_ratings: 608,
    product_url: "https://www.amazon.in/dp/B0BH87KJ8K",
    product_photo:
      "https://m.media-amazon.com/images/I/619sYCOLeqL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 4,
    product_minimum_offer_price: "₹27,590",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "100+ bought in past month",
    delivery: "FREE delivery by Wed, 21 Aug, 7:00 am - 9:00 pm",
    has_variations: false,
  },
  {
    asin: "B083G1NDTK",
    product_title:
      "Whirlpool 9 Kg 5 Star Ace XL Semi-Automatic Top Loading Washing Machine (ACE XL 9, Graphite Grey, 3D Scrub Technology)",
    product_price: "₹14,185",
    product_original_price: "₹17,200",
    currency: "INR",
    product_star_rating: "4.1",
    product_num_ratings: 1054,
    product_url: "https://www.amazon.in/dp/B083G1NDTK",
    product_photo:
      "https://m.media-amazon.com/images/I/71kWAivXg9L._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹14,185",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "M.R.P: ",
    delivery: null,
    has_variations: false,
  },
  {
    asin: "B0B38MM267",
    product_title:
      "IFB 10.0 Kg 5 Star Top Load Washing Machine Aqua Conserve (TL-SIBS 10.0KG AQUA, Inox, Power Dual Steam, Inbuilt Heater)",
    product_price: "₹32,500",
    product_original_price: "₹36,990",
    currency: "INR",
    product_star_rating: "3.6",
    product_num_ratings: 197,
    product_url: "https://www.amazon.in/dp/B0B38MM267",
    product_photo:
      "https://m.media-amazon.com/images/I/616D28KxEyL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 6,
    product_minimum_offer_price: "₹30,020",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "M.R.P: ",
    delivery: "FREE delivery by Wed, 21 Aug, 7:00 am - 9:00 pm",
    has_variations: false,
  },
  {
    asin: "B082T6CKGK",
    product_title:
      "Panasonic 8 kg 5 Star Semi-Automatic Top Loading Washing Machine with Powerful Motor (NA-W80B5ARB, Blue, Active Foam System)",
    product_price: null,
    product_original_price: null,
    currency: null,
    product_star_rating: "4.2",
    product_num_ratings: 84,
    product_url: "https://www.amazon.in/dp/B082T6CKGK",
    product_photo:
      "https://m.media-amazon.com/images/I/61QDzMsFJhL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹14,712",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "No featured offers available",
    delivery: null,
    has_variations: false,
  },
  {
    asin: "B08SR372S7",
    product_title:
      "Bosch 7 kg 5 Star Fully-Automatic Front Loading Washing Machine (WAJ2416SIN, Silver, AI active water plus, In-Built Heater)",
    product_price: "₹30,490",
    product_original_price: "₹48,590",
    currency: "INR",
    product_star_rating: "4.4",
    product_num_ratings: 3427,
    product_url: "https://www.amazon.in/dp/B08SR372S7",
    product_photo:
      "https://m.media-amazon.com/images/I/71ROlxCr9xL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹30,490",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "200+ bought in past month",
    delivery: "FREE delivery by Wed, 21 Aug, 7:00 am - 8:00 pm",
    has_variations: false,
  },
  {
    asin: "B0B38NTY9K",
    product_title:
      "IFB 7.0 Kg 5 Star Top Load Washing Machine Aqua Conserve (TL-REGS 7.0KG AQUA, Medium Grey, 2X Power Steam, 4 Years Comprehensive Warranty)",
    product_price: "₹21,450",
    product_original_price: "₹24,350",
    currency: "INR",
    product_star_rating: "4.2",
    product_num_ratings: 104,
    product_url: "https://www.amazon.in/dp/B0B38NTY9K",
    product_photo:
      "https://m.media-amazon.com/images/I/61aEf-fgerL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 2,
    product_minimum_offer_price: "₹20,990",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "100+ bought in past month",
    delivery: "FREE delivery by Wed, 21 Aug, 7:00 am - 9:00 pm",
    has_variations: false,
  },
  {
    asin: "B09H5PG724",
    product_title:
      "Panasonic 7 kg 5 Star Semi-Automatic Top Loading Washing Machine with Powerful Motor (NA-W70B5RRB, Red, Active Foam System)",
    product_price: null,
    product_original_price: null,
    currency: null,
    product_star_rating: "4.1",
    product_num_ratings: 18,
    product_url: "https://www.amazon.in/dp/B09H5PG724",
    product_photo:
      "https://m.media-amazon.com/images/I/71fZDULi8aL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 4,
    product_minimum_offer_price: "₹12,200",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "No featured offers available",
    delivery: null,
    has_variations: false,
  },
  {
    asin: "B0BHSL6LDK",
    product_title:
      "IFB 9 Kg 5 Star Front Load Washing Machine 2X Power Steam (EXECUTIVE PLUS MXS, Mocha, In-built Heater, 4 years Comprehensive Warranty)",
    product_price: "₹38,990",
    product_original_price: "₹49,990",
    currency: "INR",
    product_star_rating: "3.6",
    product_num_ratings: 38,
    product_url: "https://www.amazon.in/dp/B0BHSL6LDK",
    product_photo:
      "https://m.media-amazon.com/images/I/61huL77sceL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 3,
    product_minimum_offer_price: "₹37,990",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "M.R.P: ",
    delivery: "FREE delivery by Wed, 21 Aug, 7:00 am - 9:00 pm",
    has_variations: false,
  },
  {
    asin: "B08Q9RDT1S",
    product_title:
      "IFB Laundrimagic 3-in-1 8.5/6.5/2.5 Kg Inverter Washer Dryer Refresh(Executive ZXS, Silver)",
    product_price: "₹57,990",
    product_original_price: "₹73,990",
    currency: "INR",
    product_star_rating: "3.8",
    product_num_ratings: 244,
    product_url: "https://www.amazon.in/dp/B08Q9RDT1S",
    product_photo:
      "https://m.media-amazon.com/images/I/612akS+4pmL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 4,
    product_minimum_offer_price: "₹56,770",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "M.R.P: ",
    delivery: "FREE delivery by Wed, 21 Aug, 7:00 am - 9:00 pm",
    has_variations: false,
  },
  {
    asin: "B09N9NMF3G",
    product_title:
      "IFB 7 Kg 5 Star Front Load Washing Machine 2X Power Steam (SERENA ZSS 7010, Silver &amp; Black, In-built Heater, 4 years Comprehensive Warranty)",
    product_price: "₹32,300",
    product_original_price: "₹38,990",
    currency: "INR",
    product_star_rating: "4.3",
    product_num_ratings: 537,
    product_url: "https://www.amazon.in/dp/B09N9NMF3G",
    product_photo:
      "https://m.media-amazon.com/images/I/61CX9znaEXL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 5,
    product_minimum_offer_price: "₹32,190",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "M.R.P: ",
    delivery: "FREE delivery by Wed, 21 Aug, 7:00 am - 9:00 pm",
    has_variations: false,
  },
  {
    asin: "B08M643JST",
    product_title:
      "IFB 8 Kg 5 Star AI Powered Fully Automatic Front Load Washing Machine Steam Refresh (SENATOR WSS 8014, Silver, In-built Heater, 4 years Comprehensive Warranty)",
    product_price: "₹37,390",
    product_original_price: "₹51,690",
    currency: "INR",
    product_star_rating: "4.2",
    product_num_ratings: 954,
    product_url: "https://www.amazon.in/dp/B08M643JST",
    product_photo:
      "https://m.media-amazon.com/images/I/81ikggdCoHL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 6,
    product_minimum_offer_price: "₹36,390",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "M.R.P: ",
    delivery: "FREE delivery by Wed, 21 Aug, 7:00 am - 9:00 pm",
    has_variations: false,
  },
  {
    asin: "B09T6TL8ZR",
    product_title:
      "Samsung 9 kg, 5 Star, Digital Inverter Motor, Fully-Automatic Front Load Washing Machine (WW90T4040CX1TL, Hygiene Steam, Inox)",
    product_price: null,
    product_original_price: null,
    currency: null,
    product_star_rating: "4.4",
    product_num_ratings: 61,
    product_url: "https://www.amazon.in/dp/B09T6TL8ZR",
    product_photo:
      "https://m.media-amazon.com/images/I/71xAvMvlEEL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 3,
    product_minimum_offer_price: "₹39,990",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "No featured offers available",
    delivery: null,
    has_variations: false,
  },
  {
    asin: "B08PZ81NKP",
    product_title:
      "Bosch 8 kg 5 Star Fully-Automatic Front Loading Washing Machine (WAJ24261IN, White, AI active water plus, In-Built Heater)",
    product_price: "₹36,990",
    product_original_price: "₹43,399",
    currency: "INR",
    product_star_rating: "4.3",
    product_num_ratings: 867,
    product_url: "https://www.amazon.in/dp/B08PZ81NKP",
    product_photo:
      "https://m.media-amazon.com/images/I/716S0SapjCL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "₹36,990",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    product_availability: "Only 1 left in stock.",
    climate_pledge_friendly: false,
    sales_volume: "M.R.P: ",
    delivery:
      "FREE delivery by Wed, 21 Aug, 7:00 am - 8:00 pmOnly 1 left in stock.",
    has_variations: false,
  },
  {
    asin: "B08HNW9FNY",
    product_title:
      "IFB 6.5 Kg 5 Star Fully Automatic Top Load Washing Machine Aqua Conserve (TL-RSS 6.5KG AQUA, Light Grey, Hard Water Wash, 4 Years Comprehensive Warranty)",
    product_price: "₹19,200",
    product_original_price: "₹26,550",
    currency: "INR",
    product_star_rating: "4.3",
    product_num_ratings: 914,
    product_url: "https://www.amazon.in/dp/B08HNW9FNY",
    product_photo:
      "https://m.media-amazon.com/images/I/61d9tjYBGVL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 3,
    product_minimum_offer_price: "₹18,900",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "M.R.P: ",
    delivery: "FREE delivery by Wed, 21 Aug, 7:00 am - 9:00 pm",
    has_variations: false,
  },
  {
    asin: "B0BBMXTQMY",
    product_title:
      "LG 8 Kg 5 Star Inverter Wi-Fi Fully-Automatic Front Loading Washing Machine with Inbuilt heater (FHP1208Z5M, Middle Black, AI DD Technology &amp; Steam for Hygiene)",
    product_price: null,
    product_original_price: null,
    currency: null,
    product_star_rating: "4.3",
    product_num_ratings: 42,
    product_url: "https://www.amazon.in/dp/B0BBMXTQMY",
    product_photo:
      "https://m.media-amazon.com/images/I/71yLa2NOx5L._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 2,
    product_minimum_offer_price: "₹40,099",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "No featured offers available",
    delivery: null,
    has_variations: false,
  },
];
